export const mockApiResponse = {
  result: {
    totalCount: 36,
    items: [
      {
        name: "Adb",
        surname: "",
        userName: "ad@metapolitan.io",
        emailAddress: "ad@metapolitan.io",
        lockoutEndDateUtc: null,
        phoneNumber: "+4366565639999",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2025-04-17T19:31:21.4652572",
        id: 34,
      },
      {
        name: "admin",
        surname: "admin",
        userName: "admin",
        emailAddress: "admin@defaulttenant.com",
        lockoutEndDateUtc: null,
        phoneNumber: null,
        profilePictureId: null,
        isEmailConfirmed: true,
        roles: [
          {
            roleId: 2,
            roleName: "Admin",
          },
        ],
        isActive: true,
        creationTime: "2024-12-05T20:23:40.807528",
        id: 2,
      },
      {
        name: "Amin",
        surname: "Ganjali",
        userName: "am.ganjeali+vero10@gmail.com",
        emailAddress: "am.ganjeali+vero10@gmail.com",
        lockoutEndDateUtc: null,
        phoneNumber: "+4366565541291",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2024-12-20T10:01:01.6196088",
        id: 22,
      },
      {
        name: "Amin",
        surname: "Ganjali",
        userName: "am.ganjeali+verodev12@gmail.com",
        emailAddress: "am.ganjeali+verodev12@gmail.com",
        lockoutEndDateUtc: null,
        phoneNumber: "+436765426200",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2025-04-14T09:53:18.9057491",
        id: 29,
      },
      {
        name: "Amir",
        surname: "",
        userName: "aardalan88@gmail.com",
        emailAddress: "aardalan88@gmail.com",
        lockoutEndDateUtc: null,
        phoneNumber: "+989196475280",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2025-04-17T21:15:57.912281",
        id: 35,
      },
      {
        name: "Amir",
        surname: "",
        userName: "aardalan88@gmail.com",
        emailAddress: "aardalan88@gmail.com",
        lockoutEndDateUtc: null,
        phoneNumber: "+989196475280",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2025-04-17T21:15:57.933979",
        id: 36,
      },
      {
        name: "Amir",
        surname: "Alian",
        userName: "alian.amir.alian@gmail.com",
        emailAddress: "alian.amir.alian@gmail.com",
        lockoutEndDateUtc: null,
        phoneNumber: "+436706011150",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2025-07-06T10:59:19.2309425",
        id: 61,
      },
      {
        name: "amirhosein",
        surname: "amirhosein",
        userName: "amirhosein",
        emailAddress: "amirhoseinrajabi07@gmail.com",
        lockoutEndDateUtc: null,
        phoneNumber: "",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [
          {
            roleId: 3,
            roleName: "User",
          },
        ],
        isActive: true,
        creationTime: "2025-07-14T21:31:24.1869163",
        id: 62,
      },
      {
        name: "Antoine",
        surname: "Lavail",
        userName: "antoine@vero.co",
        emailAddress: "antoine@vero.co",
        lockoutEndDateUtc: null,
        phoneNumber: "+33650558350",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2025-04-18T20:05:07.7719868",
        id: 43,
      },
      {
        name: "Antoine",
        surname: "Lavail",
        userName: "antoine@vero.co",
        emailAddress: "antoine@vero.co",
        lockoutEndDateUtc: null,
        phoneNumber: "+33650558350",
        profilePictureId: null,
        isEmailConfirmed: false,
        roles: [],
        isActive: true,
        creationTime: "2025-04-18T20:05:07.7630393",
        id: 44,
      },
    ],
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true,
};

// Additional mock data for departments (since it's not in the API response)
export const mockDepartments = [
  "Engineering",
  "IT",
  "Marketing",
  "Sales",
  "HR",
  "Finance",
];

// Function to randomly assign departments to users
export const assignRandomDepartment = () => {
  return mockDepartments[Math.floor(Math.random() * mockDepartments.length)];
};

// Function to calculate last login (mock data)
export const getRandomLastLogin = () => {
  const options = [
    "5 minutes ago",
    "2 hours ago",
    "1 day ago",
    "3 days ago",
    "1 week ago",
    "2 weeks ago",
    "1 month ago",
  ];
  return options[Math.floor(Math.random() * options.length)];
};
